# -*- coding: utf-8 -*-
"""Swatu Sholat Asky_TI04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BrtdhGa1FjRov-HcuQGdN_IDWVbkewN-
"""

print ('Nomor 1')
Kendaraan = ['C70', 'Motor','72','White','2']
print(Kendaraan)
Kendaraan.append(17500000)
Kendaraan.append('manual')
print(Kendaraan)
Kendaraan.insert(2,'Honda')
print(Kendaraan)

print ('Nomor 2')
print ('1 Menghitung Persegi')
print ('2 Menghitung Lingkaran')
print ('3 Menghitung Segitiga')
an = input('mau ngitung apa nih ngab?')

match an :
  case '1' :
    sisi = int(input('masukkan sisi :'))
    persegi = sisi * sisi
    print ('hasil luas persegi :' , persegi)
  case '2' :
   luas = v*r*r
   v = 22/7
   r = int(input('masukkan jari2 :'))
   print('hasil luas lingkaran :', luas)
  case '3' :
    a = int(input('masukkan alas :'))
    t = int(input('masukkan tinggi :'))
    luassegi = a*t/2
    print('hasil luas segitiga :' , luassegi)
  case _:
    print('masukkan sesuai')

bilangan = int(input("masukkan bilangan :"))

if bilangan % 2 == 0:
  print ('bilangan genap')
else :
  print('bilangan ganjil')